// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Proto/services.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========================================================================== //
type GetServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string  `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Version []int32 `protobuf:"varint,2,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetServerReq) Reset() {
	*x = GetServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerReq) ProtoMessage() {}

func (x *GetServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerReq.ProtoReflect.Descriptor instead.
func (*GetServerReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetServerReq) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetServerResp) Reset() {
	*x = GetServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResp) ProtoMessage() {}

func (x *GetServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResp.ProtoReflect.Descriptor instead.
func (*GetServerResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// ========================================================================== //
type GetRebeldsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet  string  `protobuf:"bytes,1,opt,name=planet,proto3" json:"planet,omitempty"`
	City    string  `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Server  int32   `protobuf:"varint,3,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,4,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRebeldsReq) Reset() {
	*x = GetRebeldsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRebeldsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebeldsReq) ProtoMessage() {}

func (x *GetRebeldsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebeldsReq.ProtoReflect.Descriptor instead.
func (*GetRebeldsReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetRebeldsReq) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *GetRebeldsReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetRebeldsReq) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *GetRebeldsReq) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetRebeldsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammount int32   `protobuf:"varint,1,opt,name=ammount,proto3" json:"ammount,omitempty"`
	Server  int32   `protobuf:"varint,2,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,3,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRebeldsResp) Reset() {
	*x = GetRebeldsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRebeldsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebeldsResp) ProtoMessage() {}

func (x *GetRebeldsResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebeldsResp.ProtoReflect.Descriptor instead.
func (*GetRebeldsResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetRebeldsResp) GetAmmount() int32 {
	if x != nil {
		return x.Ammount
	}
	return 0
}

func (x *GetRebeldsResp) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *GetRebeldsResp) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

// ========================================================================== //
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string  `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Version []int32 `protobuf:"varint,2,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    int32   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version []int32 `protobuf:"varint,3,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *Data) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Data) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_Proto_services_proto protoreflect.FileDescriptor

var file_Proto_services_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x46, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x71, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x7b, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x32, 0x69, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12,
	0x23, 0x0a, 0x04, 0x43, 0x52, 0x55, 0x44, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c,
	0x64, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62,
	0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x49,
	0x49, 0x41, 0x73, 0x6d, 0x6f, 0x64, 0x65, 0x75, 0x73, 0x49, 0x49, 0x49, 0x2f, 0x54, 0x61, 0x72,
	0x65, 0x61, 0x33, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Proto_services_proto_rawDescOnce sync.Once
	file_Proto_services_proto_rawDescData = file_Proto_services_proto_rawDesc
)

func file_Proto_services_proto_rawDescGZIP() []byte {
	file_Proto_services_proto_rawDescOnce.Do(func() {
		file_Proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_services_proto_rawDescData)
	})
	return file_Proto_services_proto_rawDescData
}

var file_Proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Proto_services_proto_goTypes = []interface{}{
	(*GetServerReq)(nil),   // 0: grpc.GetServerReq
	(*GetServerResp)(nil),  // 1: grpc.GetServerResp
	(*GetRebeldsReq)(nil),  // 2: grpc.GetRebeldsReq
	(*GetRebeldsResp)(nil), // 3: grpc.GetRebeldsResp
	(*Command)(nil),        // 4: grpc.Command
	(*Data)(nil),           // 5: grpc.Data
}
var file_Proto_services_proto_depIdxs = []int32{
	0, // 0: grpc.Broker.GetServer:input_type -> grpc.GetServerReq
	2, // 1: grpc.Broker.GetRebelds:input_type -> grpc.GetRebeldsReq
	4, // 2: grpc.Fulcrum.CRUD:input_type -> grpc.Command
	2, // 3: grpc.Fulcrum.GetRebelds:input_type -> grpc.GetRebeldsReq
	1, // 4: grpc.Broker.GetServer:output_type -> grpc.GetServerResp
	3, // 5: grpc.Broker.GetRebelds:output_type -> grpc.GetRebeldsResp
	5, // 6: grpc.Fulcrum.CRUD:output_type -> grpc.Data
	3, // 7: grpc.Fulcrum.GetRebelds:output_type -> grpc.GetRebeldsResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_services_proto_init() }
func file_Proto_services_proto_init() {
	if File_Proto_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRebeldsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRebeldsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_Proto_services_proto_goTypes,
		DependencyIndexes: file_Proto_services_proto_depIdxs,
		MessageInfos:      file_Proto_services_proto_msgTypes,
	}.Build()
	File_Proto_services_proto = out.File
	file_Proto_services_proto_rawDesc = nil
	file_Proto_services_proto_goTypes = nil
	file_Proto_services_proto_depIdxs = nil
}
