// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	GetServer(ctx context.Context, in *GetServerReq, opts ...grpc.CallOption) (*GetServerResp, error)
	GetRebelds(ctx context.Context, in *GetRebeldsReq, opts ...grpc.CallOption) (*GetRebeldsResp, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetServer(ctx context.Context, in *GetServerReq, opts ...grpc.CallOption) (*GetServerResp, error) {
	out := new(GetServerResp)
	err := c.cc.Invoke(ctx, "/grpc.Broker/GetServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetRebelds(ctx context.Context, in *GetRebeldsReq, opts ...grpc.CallOption) (*GetRebeldsResp, error) {
	out := new(GetRebeldsResp)
	err := c.cc.Invoke(ctx, "/grpc.Broker/GetRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	GetServer(context.Context, *GetServerReq) (*GetServerResp, error)
	GetRebelds(context.Context, *GetRebeldsReq) (*GetRebeldsResp, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) GetServer(context.Context, *GetServerReq) (*GetServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServer not implemented")
}
func (UnimplementedBrokerServer) GetRebelds(context.Context, *GetRebeldsReq) (*GetRebeldsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRebelds not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Broker/GetServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetServer(ctx, req.(*GetServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRebeldsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Broker/GetRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetRebelds(ctx, req.(*GetRebeldsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServer",
			Handler:    _Broker_GetServer_Handler,
		},
		{
			MethodName: "GetRebelds",
			Handler:    _Broker_GetRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto/services.proto",
}

// FulcrumClient is the client API for Fulcrum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulcrumClient interface {
	CRUD(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Data, error)
	GetRebelds(ctx context.Context, in *GetRebeldsReq, opts ...grpc.CallOption) (*GetRebeldsResp, error)
	Merge(ctx context.Context, in *MergeReq, opts ...grpc.CallOption) (Fulcrum_MergeClient, error)
	SwitchBlock(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockResp, error)
	File(ctx context.Context, opts ...grpc.CallOption) (Fulcrum_FileClient, error)
}

type fulcrumClient struct {
	cc grpc.ClientConnInterface
}

func NewFulcrumClient(cc grpc.ClientConnInterface) FulcrumClient {
	return &fulcrumClient{cc}
}

func (c *fulcrumClient) CRUD(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/grpc.Fulcrum/CRUD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumClient) GetRebelds(ctx context.Context, in *GetRebeldsReq, opts ...grpc.CallOption) (*GetRebeldsResp, error) {
	out := new(GetRebeldsResp)
	err := c.cc.Invoke(ctx, "/grpc.Fulcrum/GetRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumClient) Merge(ctx context.Context, in *MergeReq, opts ...grpc.CallOption) (Fulcrum_MergeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Fulcrum_ServiceDesc.Streams[0], "/grpc.Fulcrum/Merge", opts...)
	if err != nil {
		return nil, err
	}
	x := &fulcrumMergeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fulcrum_MergeClient interface {
	Recv() (*MergeResp, error)
	grpc.ClientStream
}

type fulcrumMergeClient struct {
	grpc.ClientStream
}

func (x *fulcrumMergeClient) Recv() (*MergeResp, error) {
	m := new(MergeResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fulcrumClient) SwitchBlock(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockResp, error) {
	out := new(BlockResp)
	err := c.cc.Invoke(ctx, "/grpc.Fulcrum/SwitchBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumClient) File(ctx context.Context, opts ...grpc.CallOption) (Fulcrum_FileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Fulcrum_ServiceDesc.Streams[1], "/grpc.Fulcrum/File", opts...)
	if err != nil {
		return nil, err
	}
	x := &fulcrumFileClient{stream}
	return x, nil
}

type Fulcrum_FileClient interface {
	Send(*FileSend) error
	CloseAndRecv() (*FileResp, error)
	grpc.ClientStream
}

type fulcrumFileClient struct {
	grpc.ClientStream
}

func (x *fulcrumFileClient) Send(m *FileSend) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fulcrumFileClient) CloseAndRecv() (*FileResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FulcrumServer is the server API for Fulcrum service.
// All implementations must embed UnimplementedFulcrumServer
// for forward compatibility
type FulcrumServer interface {
	CRUD(context.Context, *Command) (*Data, error)
	GetRebelds(context.Context, *GetRebeldsReq) (*GetRebeldsResp, error)
	Merge(*MergeReq, Fulcrum_MergeServer) error
	SwitchBlock(context.Context, *BlockReq) (*BlockResp, error)
	File(Fulcrum_FileServer) error
	mustEmbedUnimplementedFulcrumServer()
}

// UnimplementedFulcrumServer must be embedded to have forward compatible implementations.
type UnimplementedFulcrumServer struct {
}

func (UnimplementedFulcrumServer) CRUD(context.Context, *Command) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CRUD not implemented")
}
func (UnimplementedFulcrumServer) GetRebelds(context.Context, *GetRebeldsReq) (*GetRebeldsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRebelds not implemented")
}
func (UnimplementedFulcrumServer) Merge(*MergeReq, Fulcrum_MergeServer) error {
	return status.Errorf(codes.Unimplemented, "method Merge not implemented")
}
func (UnimplementedFulcrumServer) SwitchBlock(context.Context, *BlockReq) (*BlockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchBlock not implemented")
}
func (UnimplementedFulcrumServer) File(Fulcrum_FileServer) error {
	return status.Errorf(codes.Unimplemented, "method File not implemented")
}
func (UnimplementedFulcrumServer) mustEmbedUnimplementedFulcrumServer() {}

// UnsafeFulcrumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulcrumServer will
// result in compilation errors.
type UnsafeFulcrumServer interface {
	mustEmbedUnimplementedFulcrumServer()
}

func RegisterFulcrumServer(s grpc.ServiceRegistrar, srv FulcrumServer) {
	s.RegisterService(&Fulcrum_ServiceDesc, srv)
}

func _Fulcrum_CRUD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServer).CRUD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Fulcrum/CRUD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServer).CRUD(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fulcrum_GetRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRebeldsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServer).GetRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Fulcrum/GetRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServer).GetRebelds(ctx, req.(*GetRebeldsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fulcrum_Merge_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MergeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FulcrumServer).Merge(m, &fulcrumMergeServer{stream})
}

type Fulcrum_MergeServer interface {
	Send(*MergeResp) error
	grpc.ServerStream
}

type fulcrumMergeServer struct {
	grpc.ServerStream
}

func (x *fulcrumMergeServer) Send(m *MergeResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Fulcrum_SwitchBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServer).SwitchBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Fulcrum/SwitchBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServer).SwitchBlock(ctx, req.(*BlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fulcrum_File_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FulcrumServer).File(&fulcrumFileServer{stream})
}

type Fulcrum_FileServer interface {
	SendAndClose(*FileResp) error
	Recv() (*FileSend, error)
	grpc.ServerStream
}

type fulcrumFileServer struct {
	grpc.ServerStream
}

func (x *fulcrumFileServer) SendAndClose(m *FileResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fulcrumFileServer) Recv() (*FileSend, error) {
	m := new(FileSend)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Fulcrum_ServiceDesc is the grpc.ServiceDesc for Fulcrum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fulcrum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Fulcrum",
	HandlerType: (*FulcrumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CRUD",
			Handler:    _Fulcrum_CRUD_Handler,
		},
		{
			MethodName: "GetRebelds",
			Handler:    _Fulcrum_GetRebelds_Handler,
		},
		{
			MethodName: "SwitchBlock",
			Handler:    _Fulcrum_SwitchBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Merge",
			Handler:       _Fulcrum_Merge_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "File",
			Handler:       _Fulcrum_File_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Proto/services.proto",
}
