// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Proto/services.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========================================================================== //
type GetServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string  `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Version []int32 `protobuf:"varint,2,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetServerReq) Reset() {
	*x = GetServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerReq) ProtoMessage() {}

func (x *GetServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerReq.ProtoReflect.Descriptor instead.
func (*GetServerReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetServerReq) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetServerResp) Reset() {
	*x = GetServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResp) ProtoMessage() {}

func (x *GetServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResp.ProtoReflect.Descriptor instead.
func (*GetServerResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// ========================================================================== //
type GetRebeldsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet  string  `protobuf:"bytes,1,opt,name=planet,proto3" json:"planet,omitempty"`
	City    string  `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Server  int32   `protobuf:"varint,3,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,4,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRebeldsReq) Reset() {
	*x = GetRebeldsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRebeldsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebeldsReq) ProtoMessage() {}

func (x *GetRebeldsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebeldsReq.ProtoReflect.Descriptor instead.
func (*GetRebeldsReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetRebeldsReq) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *GetRebeldsReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetRebeldsReq) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *GetRebeldsReq) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetRebeldsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammount int32   `protobuf:"varint,1,opt,name=ammount,proto3" json:"ammount,omitempty"`
	Server  int32   `protobuf:"varint,2,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,3,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRebeldsResp) Reset() {
	*x = GetRebeldsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRebeldsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebeldsResp) ProtoMessage() {}

func (x *GetRebeldsResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebeldsResp.ProtoReflect.Descriptor instead.
func (*GetRebeldsResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetRebeldsResp) GetAmmount() int32 {
	if x != nil {
		return x.Ammount
	}
	return 0
}

func (x *GetRebeldsResp) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *GetRebeldsResp) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

// ========================================================================== //
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string  `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Version []int32 `protobuf:"varint,2,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Server  int32   `protobuf:"varint,2,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,3,rep,packed,name=version,proto3" json:"version,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Data) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *Data) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

// ========================================================================== //
type MergeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *MergeReq) Reset() {
	*x = MergeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeReq) ProtoMessage() {}

func (x *MergeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeReq.ProtoReflect.Descriptor instead.
func (*MergeReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{6}
}

func (x *MergeReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type MergeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server  int32   `protobuf:"varint,1,opt,name=server,proto3" json:"server,omitempty"`
	Version []int32 `protobuf:"varint,2,rep,packed,name=version,proto3" json:"version,omitempty"`
	Command string  `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *MergeResp) Reset() {
	*x = MergeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResp) ProtoMessage() {}

func (x *MergeResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResp.ProtoReflect.Descriptor instead.
func (*MergeResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{7}
}

func (x *MergeResp) GetServer() int32 {
	if x != nil {
		return x.Server
	}
	return 0
}

func (x *MergeResp) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *MergeResp) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type BlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BlockReq) Reset() {
	*x = BlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReq) ProtoMessage() {}

func (x *BlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReq.ProtoReflect.Descriptor instead.
func (*BlockReq) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{8}
}

func (x *BlockReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type BlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BlockResp) Reset() {
	*x = BlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResp) ProtoMessage() {}

func (x *BlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResp.ProtoReflect.Descriptor instead.
func (*BlockResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{9}
}

func (x *BlockResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type FileSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *FileSend) Reset() {
	*x = FileSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSend) ProtoMessage() {}

func (x *FileSend) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSend.ProtoReflect.Descriptor instead.
func (*FileSend) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{10}
}

func (x *FileSend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileSend) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type FileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *FileResp) Reset() {
	*x = FileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_services_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp) ProtoMessage() {}

func (x *FileResp) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_services_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp.ProtoReflect.Descriptor instead.
func (*FileResp) Descriptor() ([]byte, []int) {
	return file_Proto_services_proto_rawDescGZIP(), []int{11}
}

func (x *FileResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_Proto_services_proto protoreflect.FileDescriptor

var file_Proto_services_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x46, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x71, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x57, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x1e,
	0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x1f,
	0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x32, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x7b, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x36, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x32, 0xf5, 0x01, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x04,
	0x43, 0x52, 0x55, 0x44, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x1a, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x05,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x0b, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x49, 0x49, 0x41, 0x73, 0x6d, 0x6f, 0x64, 0x65,
	0x75, 0x73, 0x49, 0x49, 0x49, 0x2f, 0x54, 0x61, 0x72, 0x65, 0x61, 0x33, 0x2f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_services_proto_rawDescOnce sync.Once
	file_Proto_services_proto_rawDescData = file_Proto_services_proto_rawDesc
)

func file_Proto_services_proto_rawDescGZIP() []byte {
	file_Proto_services_proto_rawDescOnce.Do(func() {
		file_Proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_services_proto_rawDescData)
	})
	return file_Proto_services_proto_rawDescData
}

var file_Proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_Proto_services_proto_goTypes = []interface{}{
	(*GetServerReq)(nil),   // 0: grpc.GetServerReq
	(*GetServerResp)(nil),  // 1: grpc.GetServerResp
	(*GetRebeldsReq)(nil),  // 2: grpc.GetRebeldsReq
	(*GetRebeldsResp)(nil), // 3: grpc.GetRebeldsResp
	(*Command)(nil),        // 4: grpc.Command
	(*Data)(nil),           // 5: grpc.Data
	(*MergeReq)(nil),       // 6: grpc.MergeReq
	(*MergeResp)(nil),      // 7: grpc.MergeResp
	(*BlockReq)(nil),       // 8: grpc.BlockReq
	(*BlockResp)(nil),      // 9: grpc.BlockResp
	(*FileSend)(nil),       // 10: grpc.FileSend
	(*FileResp)(nil),       // 11: grpc.FileResp
}
var file_Proto_services_proto_depIdxs = []int32{
	0,  // 0: grpc.Broker.GetServer:input_type -> grpc.GetServerReq
	2,  // 1: grpc.Broker.GetRebelds:input_type -> grpc.GetRebeldsReq
	4,  // 2: grpc.Fulcrum.CRUD:input_type -> grpc.Command
	2,  // 3: grpc.Fulcrum.GetRebelds:input_type -> grpc.GetRebeldsReq
	6,  // 4: grpc.Fulcrum.Merge:input_type -> grpc.MergeReq
	8,  // 5: grpc.Fulcrum.SwitchBlock:input_type -> grpc.BlockReq
	10, // 6: grpc.Fulcrum.File:input_type -> grpc.FileSend
	1,  // 7: grpc.Broker.GetServer:output_type -> grpc.GetServerResp
	3,  // 8: grpc.Broker.GetRebelds:output_type -> grpc.GetRebeldsResp
	5,  // 9: grpc.Fulcrum.CRUD:output_type -> grpc.Data
	3,  // 10: grpc.Fulcrum.GetRebelds:output_type -> grpc.GetRebeldsResp
	7,  // 11: grpc.Fulcrum.Merge:output_type -> grpc.MergeResp
	9,  // 12: grpc.Fulcrum.SwitchBlock:output_type -> grpc.BlockResp
	11, // 13: grpc.Fulcrum.File:output_type -> grpc.FileResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_services_proto_init() }
func file_Proto_services_proto_init() {
	if File_Proto_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRebeldsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRebeldsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_services_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_Proto_services_proto_goTypes,
		DependencyIndexes: file_Proto_services_proto_depIdxs,
		MessageInfos:      file_Proto_services_proto_msgTypes,
	}.Build()
	File_Proto_services_proto = out.File
	file_Proto_services_proto_rawDesc = nil
	file_Proto_services_proto_goTypes = nil
	file_Proto_services_proto_depIdxs = nil
}
